# Generated by cucumber-sinatra. (Sun Nov 07 15:39:54 -0600 2010)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Picawing

class PicawingWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  PicawingWorld.new
end
