# Generated by cucumber-sinatra. (Thu Aug 19 12:19:55 -0500 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'application.rb')

require 'capybara'
require 'capybara/cucumber'
#require 'capybara/envjs'
require 'spec'

set(:environment, :test)

Capybara.app = Sinatra::Application.new

class PicawingWorld
#  Capybara.javascript_driver = :envjs
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  PicawingWorld.new
end
