#!/usr/bin/env ruby
env = ARGV[0]
if env
  exec("bundle exec passenger start --socket /tmp/love9.us.socket -d --log-file ~/apps/love9.us/log/error.log -e #{env}")
else
  exec("bundle exec shotgun -s thin")
end